services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - baccarat
      - dice
      - keno
      - roulette
      - slots
    networks:
      - telecasino_net

  baccarat:
    image: repasscloud/telecasino-baccaratgameservice:0.1.6
    container_name: baccarat-api
    expose:
      - "8080"
    volumes:
      - /app/volumes/baccarat:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - telecasino_net

  dice:
    image: repasscloud/telecasino-dicegameservice:0.3.5
    container_name: dice-api
    expose:
      - "8080"
    volumes:
      - /app/volumes/dice:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - telecasino_net

  keno:
    image: repasscloud/telecasino-kenogameservice:0.1.6
    container_name: keno-api
    expose:
      - "8080"
    volumes:
      - /app/volumes/keno:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - telecasino_net

  roulette:
    image: repasscloud/telecasino-roulettegameservice:0.1.6
    container_name: roulette-api
    expose:
      - "8080"
    volumes:
      - /app/volumes/roulette:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - telecasino_net

  slots:
    image: repasscloud/telecasino-slotsgameservice:0.2.1
    container_name: slots-api
    expose:
      - "8080"
    volumes:
      - /app/volumes/slots:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - telecasino_net

networks:
  telecasino_net:
    driver: bridge
